### PR TITLE
Sweet futon logo

### PR DESCRIPTION
**Pull request by jfhbrook**
Not sure how you want the logo actually stored in-code, but hopefully this json format is easy to work with.

### CODE REVIEW

**Comment by pksunkara** [comment]
Nice work. But tbh, It doesn't appear as futon logo at all. Resolution is the problem with displaying images in terminal. This is one good example of that.

-1

**Comment by dscape** [comment]
@jesusabdullah this is soooooo rad :) ahah

**Comment by dscape** [comment]
Worked it out so it looks better

**Comment by jfhbrook** [comment]
NICE

**Pull request merged**
