### PR TITLE
OMG tests!

### PR DESCRIPTION
**Pull request by julianduque**
Basic tests for `futoncli` using `specify` and `nixt`, addresses https://github.com/dscape/futoncli/issues/5
#### commands
- [x] config
- [x] document
- [x] design
- [x] database
- [x] endpoint

### CODE REVIEW

**Comment by dscape** [comment]
Nice @julianduque :)

**Comment by julianduque** [comment]
@dscape tests ready.

I'm using a local couchdb instance but I'm planning to mock some requests. Let me know your thoughts.

**Comment by dscape** [comment]
As long as it works intravis no need for mocking. What do you think?

**Comment by julianduque** [comment]
If we want travis we need to mock :)

**Comment by dscape** [comment]
Why ? :)

http://about.travis-ci.org/docs/user/database-setup/

**Comment by julianduque** [comment]
:O didn't know about that, so yes, it will work :p

**Comment by dscape** [comment]
Already set up the key  in travis

**Comment by julianduque** [comment]
Allright! Travis likes it :)

**Comment by dscape** [comment]
Merge time?

**Comment by julianduque** [comment]
Be my guest

**Pull request merged**
